<a href="https://colab.research.google.com/github/brockmanelle/Math311_LinearAlgebra_Projects/blob/main/Math311_LearningGithub_and_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the preliminary code

In [1]:
import numpy as np
from numpy import c_

ll = "loaded"

In [3]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)

    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A



print(">> The page ", ll, lll)

>> The page  loaded  correctly!


# Solving Systems using Computation:  An Overview

Suppose we wanted to solve a system like:

$$
\left\{ \begin{array}{rcr} 5x + 6y + 2z & = & -1\\ 4x + 7y + 19 z & = & 2 \\ 3y + 12z & = & 1 \\ \end{array} \right.
$$

First, we create a matrix $A$ to represent the matrix on matrix on the left.  We'll also create a column matrix, or vector, to represent the numbers on the right hand side.  We'll call that vector $\vec{b}$:

In [9]:
# create the matrix:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

# create the vector for the right hand side:
b = np.matrix([[-1], [2], [1]])

To verify that we have entered $A$ correctly, or $\vec{b}$ correctly, simply call

```
print(A)
```

 or



```
print(b)
```

and the system will display that element:



In [10]:
print(A)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]


We want to solve the augmented matrix  $\left( A \, | \, \vec{b} \right)$, so we need to create an augmented matrix.  We use:

```
 np.c_(A, b)
```
to create the augmented matrix by putting the $\vec{b}$ vector on the right of the $A$ matrix.  We'll save this new matrix as $M$:


In [6]:
M = np.c_[A,b]
print(M)

[[ 5  6  2 -1]
 [ 4  7 19  2]
 [ 0  3 12  1]]


Lastly, we'll use te function

```
rref(M)
```

to provide the reduced row echelon form of the matrix $M$.  Let's print out the result:


In [7]:
print(rref(M))

[[ 1.          0.          0.          0.45736434]
 [ 0.          1.          0.         -0.62790698]
 [-0.         -0.          1.          0.24031008]]


# Use Computation to check prior homework

We'll use Google Colab to check our solutions to the six systems below, which we solved previously using row operations:

$$
(a) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + 2y & = & 5 \\ x - 4y & = & 0 \\ \end{array} \right.
\hspace{1cm}
(b) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x + y &=& 1 \\ x + y &=& 2 \\ \end{array}
\right.
\hspace{1cm}
(c) \hspace{.5cm}
\left\{ \begin{array}{rcr} x - 3y + z & = 1 \\ x + y + 2z & = & 14 \\ \end{array}
\right.
\hspace{1cm}
(d) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x - y &=& 1 \\ -3x -3 y &=& 2 \\ \end{array}
\right.
$$


$$
(e) \hspace{.5cm}
\left\{ \begin{array}{rcr} 4y + z & = & 20 \\ 2x - 2y + z & = & 0 \\ x + z & = & 5 \\ x + y - z & = & 10 \\ \end{array} \right.
\hspace{1cm}
(f) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + z + w & = & 5 \\ y - w & = & -1 \\ 3x - z - w & = & 0 \\ 4x + y + 2z + w & = & 9 \\ \end{array}
\right.
$$




The main steps are to:

1) Create the matrix $A$ and column vector $\vec{b}$ for the system using



```
# create the matrix:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

# create the vector for the right hand side:
b = np.matrix([[-1], [2], [1]])
```


2) Create the augmented matrix $\left( A \, | \, \vec{b} \right)$ using



```
M = np.c_[A,b]
```

3)  Display the reduced row echelon form of $M$ using



```
print(rref(M))
```

You'll do this for each of the six systems of equations from the homework:


$$
(a) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + 2y & = & 5 \\ x - 4y & = & 0 \\ \end{array} \right.
$$

In [11]:
A = np.matrix([[2, 2],
               [1, -4],
               ])

In [12]:
b = np.matrix([[5], [0]])

In [13]:
M = np.c_[A,b]

In [14]:
print(rref(M))

[[1.  0.  2. ]
 [0.  1.  0.5]]


$$
(b) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x + y &=& 1 \\ x + y &=& 2 \\ \end{array}
\right.
$$

In [15]:
A = np.matrix([[-1, 1],
               [1, 1],
               ])

In [16]:
b = np.matrix([[1], [2]])

In [17]:
M = np.c_[A,b]

In [18]:
print(rref(M))

[[1.  0.  0.5]
 [0.  1.  1.5]]


$$
(c) \hspace{.5cm}
\left\{ \begin{array}{rcr} x - 3y + z & = 1 \\ x + y + 2z & = & 14 \\ \end{array}
\right.
$$

In [19]:
A = np.matrix([[1, -3, 1],
               [1, 1, 2],
               ])

In [20]:
b = np.matrix([[1], [14]])

In [21]:
M = np.c_[A,b]

In [22]:
print(rref(M))

[[ 1.    0.    1.75 10.75]
 [-0.    1.    0.25  3.25]]


$$
(d) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x - y &=& 1 \\ -3x -3 y &=& 2 \\ \end{array}
\right.
$$

In [23]:
A = np.matrix([[-1, -1],
               [-3, -3,],
               ])

In [24]:
b = np.matrix([[1], [2]])

In [25]:
M = np.c_[A,b]

In [26]:
print(rref(M))

[[1. 1. 0.]
 [0. 0. 1.]]


$$
(e) \hspace{.5cm}
\left\{ \begin{array}{rcr} 4y + z & = & 20 \\ 2x - 2y + z & = & 0 \\ x + z & = & 5 \\ x + y - z & = & 10 \\ \end{array} \right.
$$

In [28]:
A = np.matrix([[0, 4, 1],
               [2, -2, 1],
               [1, 0, 1],
               [1, 1, -1 ]
               ])

In [29]:
b = np.matrix([[20], [0], [5], [10]])

In [30]:
M = np.c_[A,b]

In [31]:
print(rref(M))

[[1. 0. 0. 5.]
 [0. 1. 0. 5.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


$$
(f) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + z + w & = & 5 \\ y - w & = & -1 \\ 3x - z - w & = & 0 \\ 4x + y + 2z + w & = & 9 \\ \end{array}
\right.
$$

In [32]:
A = np.matrix([[1, 0, 1, 1],
               [0, 1, 0, 1],
               [3, 0, -1, -1],
               [4, 1, 2, 1 ]
               ])

In [33]:
b = np.matrix([[5], [-1], [0], [9]])

In [34]:
M = np.c_[A,b]

In [35]:
print(rref(M))

[[ 1.    0.    0.    0.    1.25]
 [ 0.    1.    0.    0.   -2.25]
 [ 0.    0.    1.    0.    2.5 ]
 [ 0.    0.    0.    1.    1.25]]
